### PR TITLE
Upgrade 2.101

### LINKED ISSUE #12: Master setup is not right
I has a quick look a the source file. The hinting settings (stems) are the same in both masters. That can’t be right.

### LINKED ISSUE #20: Change the ø and Ø
They look very odd to myself (Danish is my native language) and also asked a bunch of other designers that agreed. We never do an ø or Ø like that other than maybe some display/logo fonts 🙃

It's the equivalent of having e.g. a slanted crossbar on a `t` or something.

It would look much more in place if the slash goes from bottom left to top right corner. Also would still kinda fit the typeface I'd think.

Let me know if you accept a PR and I'll fix it. 

Cheers

### LINKED ISSUE #21: · (U+00B7) is too big for use in Catalan’s “l·l”
… and since this family lacks the OpenType feature to turn the sequences ⟨l·l⟩ and ⟨L·L⟩ into something nicer (this exists in e.g. Fira Sans), Catalan typography looks quite bad by default.

It should be noted that Rubik does contain the characters “Ŀ” and “ŀ”, but these are deprecated and discouraged for Catalan typing.

### LINKED ISSUE #22: Feature "tnum" seems broken
First of all, thank you very much for designing and maintaining this font. I've looked up at least hundreds of different fonts for displaying numbers, and Rubik is at the top of my list that I can't wait to use in my next project. 

Back to the issue, I checked the .glyphs file and the fixed-width digits are already there with `.otlf` suffix, but there isn't any feature definition. This is probably broken when migrating sources from `version-1`. I am not very familiar with font editing so can't help with an PR.

Hope you can read this and have time to fix it.
Have a good day.

### LINKED ISSUE #27: Add slashed or dotted zero
It's a shame the font doesn't include this character, it's so useful when displaying identifiers 😟.

### LINKED ISSUE #30: Mathematical signs are misaligned #21
Comments by thlinard.  A foundry decision.
https://github.com/TypeNetwork/rubik/issues/21

### LINKED ISSUE #32: Missing anchors
Comb accents have anchors but a lot of letters are missing some (mostly lowercases)

### LINKED ISSUE #33: Missing ľ in italic
please could you add ľ in italic rubic fonts?

### LINKED ISSUE #34: inconsistencies between base letter and accented letters
Capture d’écran 2021-04-07 à 16 11 57

### LINKED ISSUE #35: INR symbol (Indian Rupee, ₹) is Missing
Rubik is missing the INR symbol. Can you add ₹ to this font family?

msedge_w9jFcoHhGd

### PR DESCRIPTION
**Pull request by RosaWagner**
Fixes #35 
Fixes #34
Fixes #33
Fixes #32
Fixes #30
Fixes #27
Fixes #22
Fixes #21
Fixes #20
Fixes #12

### CODE REVIEW

**Comment by RosaWagner** [comment]
## Fontbakery report

Fontbakery version: 0.7.34

<details>
<summary><b>[4] Rubik-Italic[wght].ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Are there caret positions declared for every ligature?</summary>

* [com.google.fonts/check/ligature_carets](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/ligature_carets)
<pre>--- Rationale ---

All ligatures in a font must have corresponding caret (text cursor) positions
defined in the GDEF table, otherwhise, users may experience issues with caret
rendering.

If using GlyphsApp, ligature carets can be set directly on canvas by accessing
the `Glyph -&gt; Set Anchors` menu option or by pressing the `Cmd+U` keyboard
shortcut.

If designing with UFOs, (as of Oct 2020) ligature carets are not yet compiled
by ufo2ft, and therefore will not build via FontMake. See
googlefonts/ufo2ft/issues/329


</pre>

* 🔥 **FAIL** Failed to lookup ligatures. This font file seems to be malformed. For more info, read: https://github.com/googlefonts/fontbakery/issues/1596 [code: malformed]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
<pre>--- Rationale ---

Fonts with ligatures should have kerning on the corresponding non-ligated
sequences for text where ligatures aren&#x27;t used (eg
https://github.com/impallari/Raleway/issues/14).


</pre>

* 🔥 **FAIL** Failed to lookup ligatures. This font file seems to be malformed. For more info, read: https://github.com/googlefonts/fontbakery/issues/1596 [code: malformed]

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking OS/2 achVendID.</summary>

* [com.google.fonts/check/vendor_id](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vendor_id)
<pre>--- Rationale ---

Microsoft keeps a list of font vendors and their respective contact info. This
list is updated regularly and is indexed by a 4-char &quot;Vendor ID&quot; which is
stored in the achVendID field of the OS/2 table.

Registering your ID is not mandatory, but it is a good practice since some
applications may display the type designer / type foundry contact info on some
dialog and also because that info will be visible on Microsoft&#x27;s website:

https://docs.microsoft.com/en-us/typography/vendors/

This check verifies whether or not a given font&#x27;s vendor ID is registered in
that list or if it has some of the default values used by the most common font
editors.

Each new FontBakery release includes a cached copy of that list of vendor IDs.
If you registered recently, you&#x27;re safe to ignore warnings emitted by this
check, since your ID will soon be included in one of our upcoming releases.


</pre>

* ⚠ **WARN** OS/2 VendorID value 'NONE' is not yet recognized. If you registered it recently, then it's safe to ignore this warning message. Otherwise, you should set it to your own unique 4 character code, and register it with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx
 [code: unknown]

</details>
<details>
<summary>⚠ <b>WARN:</b> Are there any misaligned on-curve points?</summary>

* [com.google.fonts/check/outline_alignment_miss](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_alignment_miss)
<pre>--- Rationale ---

This test heuristically looks for on-curve points which are close to, but do
not sit on, significant boundary coordinates. For example, a point which has a
Y-coordinate of 1 or -1 might be a misplaced baseline point. As well as the
baseline, the test also checks for points near the x-height (but only for lower
case Latin letters), cap-height, ascender and descender Y coordinates.

Not all such misaligned curve points are a mistake, and sometimes the design
may call for points in locations near the boundaries. As this test is liable to
generate significant numbers of false positives, the test will pass if there
are more than 100 reported misalignments.


</pre>

* ⚠ **WARN** The following glyphs have on-curve points which have potentially incorrect y coordinates:
	* J: X=140.5,Y=2.0 (should be at baseline 0?)
	* uni004A0301: X=140.5,Y=2.0 (should be at baseline 0?)
	* Jcircumflex: X=140.5,Y=2.0 (should be at baseline 0?)
	* aogonek: X=326.0,Y=2.0 (should be at baseline 0?)
	* ccaron: X=232.0,Y=699.0 (should be at cap-height 700?)
	* ecaron: X=246.0,Y=699.0 (should be at cap-height 700?)
	* eogonek: X=164.0,Y=-2.0 (should be at baseline 0?)
	* m: X=266.5,Y=522.0 (should be at x-height 520?)
	* ncaron: X=254.0,Y=699.0 (should be at cap-height 700?)
	* oslash: X=15.0,Y=1.0 (should be at baseline 0?) and 41 more. [code: found-misalignments]

</details>
<br>
</details>
<details>
<summary><b>[4] Rubik[wght].ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Are there caret positions declared for every ligature?</summary>

* [com.google.fonts/check/ligature_carets](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/ligature_carets)
<pre>--- Rationale ---

All ligatures in a font must have corresponding caret (text cursor) positions
defined in the GDEF table, otherwhise, users may experience issues with caret
rendering.

If using GlyphsApp, ligature carets can be set directly on canvas by accessing
the `Glyph -&gt; Set Anchors` menu option or by pressing the `Cmd+U` keyboard
shortcut.

If designing with UFOs, (as of Oct 2020) ligature carets are not yet compiled
by ufo2ft, and therefore will not build via FontMake. See
googlefonts/ufo2ft/issues/329


</pre>

* 🔥 **FAIL** Failed to lookup ligatures. This font file seems to be malformed. For more info, read: https://github.com/googlefonts/fontbakery/issues/1596 [code: malformed]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
<pre>--- Rationale ---

Fonts with ligatures should have kerning on the corresponding non-ligated
sequences for text where ligatures aren&#x27;t used (eg
https://github.com/impallari/Raleway/issues/14).


</pre>

* 🔥 **FAIL** Failed to lookup ligatures. This font file seems to be malformed. For more info, read: https://github.com/googlefonts/fontbakery/issues/1596 [code: malformed]

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking OS/2 achVendID.</summary>

* [com.google.fonts/check/vendor_id](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vendor_id)
<pre>--- Rationale ---

Microsoft keeps a list of font vendors and their respective contact info. This
list is updated regularly and is indexed by a 4-char &quot;Vendor ID&quot; which is
stored in the achVendID field of the OS/2 table.

Registering your ID is not mandatory, but it is a good practice since some
applications may display the type designer / type foundry contact info on some
dialog and also because that info will be visible on Microsoft&#x27;s website:

https://docs.microsoft.com/en-us/typography/vendors/

This check verifies whether or not a given font&#x27;s vendor ID is registered in
that list or if it has some of the default values used by the most common font
editors.

Each new FontBakery release includes a cached copy of that list of vendor IDs.
If you registered recently, you&#x27;re safe to ignore warnings emitted by this
check, since your ID will soon be included in one of our upcoming releases.


</pre>

* ⚠ **WARN** OS/2 VendorID value 'NONE' is not yet recognized. If you registered it recently, then it's safe to ignore this warning message. Otherwise, you should set it to your own unique 4 character code, and register it with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx
 [code: unknown]

</details>
<details>
<summary>⚠ <b>WARN:</b> Are there any misaligned on-curve points?</summary>

* [com.google.fonts/check/outline_alignment_miss](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_alignment_miss)
<pre>--- Rationale ---

This test heuristically looks for on-curve points which are close to, but do
not sit on, significant boundary coordinates. For example, a point which has a
Y-coordinate of 1 or -1 might be a misplaced baseline point. As well as the
baseline, the test also checks for points near the x-height (but only for lower
case Latin letters), cap-height, ascender and descender Y coordinates.

Not all such misaligned curve points are a mistake, and sometimes the design
may call for points in locations near the boundaries. As this test is liable to
generate significant numbers of false positives, the test will pass if there
are more than 100 reported misalignments.


</pre>

* ⚠ **WARN** The following glyphs have on-curve points which have potentially incorrect y coordinates:
	* J: X=196.0,Y=2.0 (should be at baseline 0?)
	* uni004A0301: X=196.0,Y=2.0 (should be at baseline 0?)
	* Jcircumflex: X=196.0,Y=2.0 (should be at baseline 0?)
	* aogonek: X=445.0,Y=1.0 (should be at baseline 0?)
	* c: X=353.5,Y=-0.5 (should be at baseline 0?)
	* cacute: X=353.5,Y=-0.5 (should be at baseline 0?)
	* ccaron: X=353.5,Y=-0.5 (should be at baseline 0?)
	* ccircumflex: X=353.5,Y=-0.5 (should be at baseline 0?)
	* cdotaccent: X=353.5,Y=-0.5 (should be at baseline 0?)
	* eogonek: X=213.0,Y=-2.0 (should be at baseline 0?) and 26 more. [code: found-misalignments]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 4 | 4 | 174 | 17 | 176 | 0 |
| 0% | 1% | 1% | 46% | 5% | 47% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**

**Comment by steffendb** [comment]
Thank you very much for updating this. Do you (or anyone else) know how long it takes for updates like this to propagate to providers like fonts.google and fonts.adobe?

**Comment by RosaWagner** [comment]
To google it will take 2 weeks or 3

**Comment by steffendb** [comment]
Thank you for the quick reply. That's great news. Someone will be very happy to see the wierd Ø and ø get fixed (#20) :) Thank you.

**Pull request merged**
