### PR TITLE
reconstructed hinting, fixes #15

### LINKED ISSUE #15: rendering issues in IE
Hey @m4rc1e, I'm trying to figure out where things went awry and I noticed that the build script produces a broken glyf table: it won't complile in VTT and that's the complaint. On the other hand, it passes MS fontval. I'm going to dig into this and this issue is essentially my notes.

### PR DESCRIPTION
**Pull request by laerm0**
This not only fixes #15 but it fixes https://github.com/google/fonts/issues/1137. Or it _should_ anyway: trying to replicate that bug that made the font disappear is not easy. I can't get the fonts to break, but I do think they need a little more testing just to make sure.

### CODE REVIEW

**Comment by laerm0** [comment]
I signed it!

**Comment by m4rc1e** [comment]
I've just generated the fonts from the .glyphs file. Each ttf contains 764 glyphs. However, In the Bold vtt src file there are 770. Imo, they should match.

**Comment by laerm0** [comment]
Oh, you're right, I forgot to get rid of a few unnecessary glyphs. I'll remove them and then push a new file this afternoon.

**Comment by davelab6** [comment]
Closing as replaced by the VF work

**Pull request closed without merging**
