### PR TITLE
Bold fix

### PR DESCRIPTION
**Pull request by laerm0**
deleted six glyphs from Bold: uniFB43.black uniFB44.black descendercy descendercy.case verticalbarcy verticalbarcy.case

### CODE REVIEW

**Comment by laerm0** [comment]
I signed it

**Comment by m4rc1e** [comment]
Can you compile and ship the fonts in this pr.

**Comment by laerm0** [comment]
The entire family or just the bold (in this PR)...?

**Comment by m4rc1e** [comment]
The entire family please.

**Comment by laerm0** [comment]
Okay. I'll put them in fonts/ttf and leave the sources in sources/hinted_ttfs.

**Comment by davelab6** [comment]
Closing as replaced by the VF work

**Pull request closed without merging**
